version: 0.2
phases:
  install: 
    commands:
       - npm install install -g @vue/cli 
       - pip install --upgrade pip
       - pip install --upgrade awscli
  build:
    commands:
       - cd src/frontend/bootstrapvue
       - npm i vue bootstrap-vue bootstrap axios
       - npm run build
  post_build:
    commands:
       - aws s3 sync ./dist s3://www.hyunwook.com
